---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/crate-ci/typos.git
    rev: v1.21.0
    hooks:
      - id: typos
  - repo: https://github.com/psf/black.git
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8.git
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==24.4.26
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
